spring:
  application:
    name: msvc-venta
  config:
    import: optional:configserver:http://localhost:8888
    
  profiles:
    active: dev

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html