server:
  port: 8060
spring:
  application:
    name: microservice-api-docs
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

springdoc:
  swagger-ui:
    urls:
      - name: productos
        url: http://localhost:8090/v3/api-docs
      - name: ventas
        url: http://localhost:9090/v3/api-docs
    path: /swagger-ui.html