server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Habilita el descubrimiento de servicios a través de Eureka
      routes:
        - id: productos
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/productos/** #Rutas que se redirigen al microservicio de prodcutos.
        - id: ventas
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/ventas/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false