server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producto
          uri: http://localhost:8090
          predicates: 
            -Path=/api/v1/producto/**
        - id: venta
          uri: http://localhost:9090
          predicates: 
            -Path=/api/v1/venta/**

eureka:
  client:
    register-with-erueka: false
    fetch-registry: false