server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientes
          uri: http://localhost:8090
          predicates: 
            -Path=/api/v1/clientes/**

eureka:
  client:
    register-with-erueka: false
    fetch-registry: false